import 'package:flutter/material.dart';

enum GameTheme {
  classic,
  cat,
  hellokitty,
  cars,
  fruits,
  powerpuffGirls,
  spiderman,
  sungerbob,
  winniePooh,
  batman,
  stitch,
}

class GameThemeData {
  final String id;
  final String name;
  final String emoji;
  final String description;

  // Background
  final Color backgroundColor;
  final Color backgroundGlow1;
  final Color backgroundGlow2;

  // Board
  final Color boardBackground;
  final Color boardBorder;
  final Color boardHole;
  final Color boardEmpty;

  // Pieces
  final Color piecePrimary;
  final Color pieceDark;
  final Color pieceHighlight;
  final Color pieceSelected;

  // Asset-based piece
  final List<String>? pieceAssets; // multiple image variants, if any
  final String? pieceAsset; // path to image asset, null = use gradient ball
  final String pieceEmoji; // fallback emoji
  final List<String> particles; // floating particles
  final bool useAssetPiece;

  // UI
  final Color primaryColor;
  final Color primaryDark;
  final Color primaryLight;
  final Color accentColor;
  final Color surfaceColor;
  final Color surfaceLight;
  final Color borderLight;
  final Color borderGlow;
  final Color validMoveColor;
  final Color textPrimary;
  final Color textSecondary;
  final Color glassColor;
  final Color glassBorder;

  const GameThemeData({
    required this.id,
    required this.name,
    required this.emoji,
    required this.description,
    required this.backgroundColor,
    required this.backgroundGlow1,
    required this.backgroundGlow2,
    required this.boardBackground,
    required this.boardBorder,
    required this.boardHole,
    required this.boardEmpty,
    required this.piecePrimary,
    required this.pieceDark,
    required this.pieceHighlight,
    required this.pieceSelected,
    this.pieceAssets,
    this.pieceAsset,
    required this.pieceEmoji,
    required this.particles,
    required this.useAssetPiece,
    required this.primaryColor,
    required this.primaryDark,
    required this.primaryLight,
    required this.accentColor,
    required this.surfaceColor,
    required this.surfaceLight,
    required this.borderLight,
    required this.borderGlow,
    required this.validMoveColor,
    required this.textPrimary,
    required this.textSecondary,
    required this.glassColor,
    required this.glassBorder,
  });
}

const classicTheme = GameThemeData(
  id: 'classic',
  name: 'KLASİK',
  emoji: '♟️',
  description: 'Derin uzay — koyu mor',
  pieceAsset: null,
  pieceEmoji: '🟣',
  particles: ['✨', '💫', '⭐', '🌟'],
  useAssetPiece: false,
  backgroundColor: Color(0xFF070712),
  backgroundGlow1: Color(0xFF7C3AED),
  backgroundGlow2: Color(0xFF06B6D4),
  boardBackground: Color(0xFF0C0A28),
  boardBorder: Color(0xFF2D1F5E),
  boardHole: Color(0xFF06041A),
  boardEmpty: Color(0xFF04030F),
  piecePrimary: Color(0xFF7C3AED),
  pieceDark: Color(0xFF5B21B6),
  pieceHighlight: Color(0xFFA78BFA),
  pieceSelected: Color(0xFF06B6D4),
  primaryColor: Color(0xFF7C3AED),
  primaryDark: Color(0xFF5B21B6),
  primaryLight: Color(0xFFA78BFA),
  accentColor: Color(0xFF06B6D4),
  surfaceColor: Color(0xFF0F0F23),
  surfaceLight: Color(0xFF1A1A35),
  borderLight: Color(0xFF1E2040),
  borderGlow: Color(0x557C3AED),
  validMoveColor: Color(0xFF10B981),
  textPrimary: Color(0xFFE2E8F0),
  textSecondary: Color(0xFF94A3B8),
  glassColor: Color(0x12FFFFFF),
  glassBorder: Color(0x20FFFFFF),
);

const hellokittyTheme = GameThemeData(
  id: 'hellokitty',
  name: 'HELLO KİTTY',
  emoji: '🎀',
  description: 'Toz pembe — kawaii dünya',
  pieceAsset: 'assets/images/hellokitty/kitty.png',
  pieceEmoji: '🐱',
  particles: ['🎀', '💕', '🌸', '⭐', '🍭', '💗'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFFDF0F5),
  backgroundGlow1: Color(0xFFFFB7D5),
  backgroundGlow2: Color(0xFFFF80AB),
  boardBackground: Color(0xFFFFF0F6),
  boardBorder: Color(0xFFFFB7D5),
  boardHole: Color(0xFFFCE4EC),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFE91E8C),
  pieceDark: Color(0xFFC2185B),
  pieceHighlight: Color(0xFFF48FB1),
  pieceSelected: Color(0xFFFF4081),
  primaryColor: Color(0xFFE91E8C),
  primaryDark: Color(0xFFC2185B),
  primaryLight: Color(0xFFF48FB1),
  accentColor: Color(0xFFFF80AB),
  surfaceColor: Color(0xFFFFF0F6),
  surfaceLight: Color(0xFFFFE4F0),
  borderLight: Color(0xFFFFB7D5),
  borderGlow: Color(0x55E91E8C),
  validMoveColor: Color(0xFFFF4081),
  textPrimary: Color(0xFF880E4F),
  textSecondary: Color(0xFFAD1457),
  glassColor: Color(0x18E91E8C),
  glassBorder: Color(0x30E91E8C),
);

const carsTheme = GameThemeData(
  id: 'cars',
  name: 'ARABALAR',
  emoji: '🏎️',
  description: 'Lightning McQueen — pist heyecanı',
  pieceAsset: 'assets/images/cars/mcqueen.png',
  pieceEmoji: '🚗',
  particles: ['🏎️', '💨', '🔥', '⚡', '🏁', '💥'],
  useAssetPiece: true,
  backgroundColor: Color(0xFF0D0503),
  backgroundGlow1: Color(0xFFD32F2F),
  backgroundGlow2: Color(0xFFFF6F00),
  boardBackground: Color(0xFF1A0800),
  boardBorder: Color(0xFF5D1A00),
  boardHole: Color(0xFF0D0500),
  boardEmpty: Color(0xFF080300),
  piecePrimary: Color(0xFFD32F2F),
  pieceDark: Color(0xFFB71C1C),
  pieceHighlight: Color(0xFFFF5252),
  pieceSelected: Color(0xFFFF6F00),
  primaryColor: Color(0xFFD32F2F),
  primaryDark: Color(0xFFB71C1C),
  primaryLight: Color(0xFFFF5252),
  accentColor: Color(0xFFFF6F00),
  surfaceColor: Color(0xFF180600),
  surfaceLight: Color(0xFF241000),
  borderLight: Color(0xFF3D1500),
  borderGlow: Color(0x55D32F2F),
  validMoveColor: Color(0xFFFFC107),
  textPrimary: Color(0xFFFFF8F0),
  textSecondary: Color(0xFFFFAB91),
  glassColor: Color(0x15FF5252),
  glassBorder: Color(0x25FF5252),
);

const fruitsTheme = GameThemeData(
  id: 'fruits',
  name: 'MEYVELER',
  emoji: '🍎',
  description: 'Renkli meyve sepeti — taze ve canlı',
  pieceAssets: [
    'assets/images/fruits/apple.png',
    'assets/images/fruits/banana.png',
    'assets/images/fruits/blueberry.png',
    'assets/images/fruits/kiwi.png',
    'assets/images/fruits/strawberry.png',
  ],
  pieceAsset: null,
  pieceEmoji: '🍎',
  particles: ['🍎', '🍌', '🫐', '🥝', '🍓', '🌱', '✨'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFF8F8F0),
  backgroundGlow1: Color(0xFFFF6B6B),
  backgroundGlow2: Color(0xFFFFD93D),
  boardBackground: Color(0xFFFBFBF5),
  boardBorder: Color(0xFFE8D5C4),
  boardHole: Color(0xFFF0EDEA),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFFF6B6B),
  pieceDark: Color(0xFFE53935),
  pieceHighlight: Color(0xFFFF8A80),
  pieceSelected: Color(0xFFFFD93D),
  primaryColor: Color(0xFFFF6B6B),
  primaryDark: Color(0xFFE53935),
  primaryLight: Color(0xFFFF8A80),
  accentColor: Color(0xFFFFD93D),
  surfaceColor: Color(0xFFFBFBF5),
  surfaceLight: Color(0xFFFDFDF9),
  borderLight: Color(0xFFE8D5C4),
  borderGlow: Color(0x55FF6B6B),
  validMoveColor: Color(0xFF6BCB77),
  textPrimary: Color(0xFF2D3142),
  textSecondary: Color(0xFF4D576A),
  glassColor: Color(0x12FF6B6B),
  glassBorder: Color(0x20FF6B6B),
);

// existing themes map is defined below with the added `cat` theme

const catTheme = GameThemeData(
  id: 'cat',
  name: 'KEDİ',
  emoji: '🐈',
  description: 'Sevimli kedi taşları',
  pieceAsset: 'assets/images/cat/cat.png',
  pieceEmoji: '🐾',
  particles: ['🐾', '✨', '😺'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFFFF8E1),
  backgroundGlow1: Color(0xFFFFE082),
  backgroundGlow2: Color(0xFFFFCC80),
  boardBackground: Color(0xFFFFF3DE),
  boardBorder: Color(0xFFFFE0B2),
  boardHole: Color(0xFFFFF7E6),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFFF8A65),
  pieceDark: Color(0xFFD9644A),
  pieceHighlight: Color(0xFFFFAB91),
  pieceSelected: Color(0xFFFF7043),
  primaryColor: Color(0xFFFF8A65),
  primaryDark: Color(0xFFD9644A),
  primaryLight: Color(0xFFFFCCBC),
  accentColor: Color(0xFFFFAB91),
  surfaceColor: Color(0xFFFFF3DE),
  surfaceLight: Color(0xFFFFF7EE),
  borderLight: Color(0xFFFFE0B2),
  borderGlow: Color(0x55FF8A65),
  validMoveColor: Color(0xFF81C784),
  textPrimary: Color(0xFF4E342E),
  textSecondary: Color(0xFF6D4C41),
  glassColor: Color(0x12FF8A65),
  glassBorder: Color(0x20FF8A65),
);

const powerpuffGirlsTheme = GameThemeData(
  id: 'powerpuffgirls',
  name: 'POWERPUFF GIRLS',
  emoji: '🌈',
  description: 'Üç kahraman, renkli ve enerjik taşlar',
  pieceAssets: [
    'assets/images/powerpuff_girls/powerpuffgirls1.png',
    'assets/images/powerpuff_girls/powerpuffgirls2.png',
    'assets/images/powerpuff_girls/powerpuffgirls3.png',
  ],
  pieceAsset: null,
  pieceEmoji: '💖',
  particles: ['💖', '💙', '💛', '✨', '🌸'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFFFF7FB),
  backgroundGlow1: Color(0xFFFFB3D9),
  backgroundGlow2: Color(0xFF89CFF0),
  boardBackground: Color(0xFFFFFAFC),
  boardBorder: Color(0xFFF5C7E0),
  boardHole: Color(0xFFFFF1F8),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFFF7EB6),
  pieceDark: Color(0xFFE64A8A),
  pieceHighlight: Color(0xFFFFB4D8),
  pieceSelected: Color(0xFF7C4DFF),
  primaryColor: Color(0xFFFF7EB6),
  primaryDark: Color(0xFFE64A8A),
  primaryLight: Color(0xFFFFB4D8),
  accentColor: Color(0xFF7C4DFF),
  surfaceColor: Color(0xFFFFFAFC),
  surfaceLight: Color(0xFFFFF0F7),
  borderLight: Color(0xFFF5C7E0),
  borderGlow: Color(0x55FF7EB6),
  validMoveColor: Color(0xFF6BCB77),
  textPrimary: Color(0xFF4A2C5A),
  textSecondary: Color(0xFF735A7F),
  glassColor: Color(0x16FF7EB6),
  glassBorder: Color(0x28FF7EB6),
);

const spidermanTheme = GameThemeData(
  id: 'spiderman',
  name: 'SPIDER-MAN',
  emoji: '🕷️',
  description: 'Örümcek adamın kırmızı-mavi enerjisi',
  pieceAssets: ['assets/images/spiderman/spiderman.png'],
  pieceAsset: null,
  pieceEmoji: '🕸️',
  particles: ['🕷️', '🕸️', '⚡', '🔥'],
  useAssetPiece: true,
  backgroundColor: Color(0xFF08111F),
  backgroundGlow1: Color(0xFFE53935),
  backgroundGlow2: Color(0xFF1E88E5),
  boardBackground: Color(0xFF0D1728),
  boardBorder: Color(0xFF223B5C),
  boardHole: Color(0xFF06101F),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFE53935),
  pieceDark: Color(0xFFB71C1C),
  pieceHighlight: Color(0xFFFF6F61),
  pieceSelected: Color(0xFF1E88E5),
  primaryColor: Color(0xFFE53935),
  primaryDark: Color(0xFFB71C1C),
  primaryLight: Color(0xFFFF6F61),
  accentColor: Color(0xFF1E88E5),
  surfaceColor: Color(0xFF101C31),
  surfaceLight: Color(0xFF17253D),
  borderLight: Color(0xFF223B5C),
  borderGlow: Color(0x55E53935),
  validMoveColor: Color(0xFF43A047),
  textPrimary: Color(0xFFF3F7FF),
  textSecondary: Color(0xFFB3C3DA),
  glassColor: Color(0x161E88E5),
  glassBorder: Color(0x241E88E5),
);

const sungerbobTheme = GameThemeData(
  id: 'sungerbob',
  name: 'SÜNGERBOB',
  emoji: '🧽',
  description: 'SüngerBob ve Patrick sırayla dizilir',
  pieceAssets: [
    'assets/images/sungerbob/sungerbob.png',
    'assets/images/sungerbob/patrick.png',
  ],
  pieceAsset: null,
  pieceEmoji: '🧽',
  particles: ['🧽', '⭐', '🌊', '🫧'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFF4FAFF),
  backgroundGlow1: Color(0xFF8DD8FF),
  backgroundGlow2: Color(0xFFB39DDB),
  boardBackground: Color(0xFFF9FDFF),
  boardBorder: Color(0xFFB9D9EE),
  boardHole: Color(0xFFF1F8FF),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFF8FD3FF),
  pieceDark: Color(0xFF1B88D3),
  pieceHighlight: Color(0xFFCFEFFF),
  pieceSelected: Color(0xFFFFA7C4),
  primaryColor: Color(0xFF8FD3FF),
  primaryDark: Color(0xFF1B88D3),
  primaryLight: Color(0xFFCFEFFF),
  accentColor: Color(0xFFFFA7C4),
  surfaceColor: Color(0xFFF9FDFF),
  surfaceLight: Color(0xFFF1F8FF),
  borderLight: Color(0xFFB9D9EE),
  borderGlow: Color(0x558FD3FF),
  validMoveColor: Color(0xFF26A69A),
  textPrimary: Color(0xFF5D4037),
  textSecondary: Color(0xFF8D6E63),
  glassColor: Color(0x168FD3FF),
  glassBorder: Color(0x248FD3FF),
);

const winniePoohTheme = GameThemeData(
  id: 'winnie_pooh',
  name: 'WINNIE POOH',
  emoji: '🐻',
  description: 'Sıcak bal tonları ve tatlı bir atmosfer',
  pieceAsset: 'assets/images/winnie_the_pooh/winnie-the-pooh.png',
  pieceEmoji: '🍯',
  particles: ['🍯', '🐻', '✨', '🌼'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFFFF6E5),
  backgroundGlow1: Color(0xFFFFD166),
  backgroundGlow2: Color(0xFFFFB74D),
  boardBackground: Color(0xFFFFF9ED),
  boardBorder: Color(0xFFE7C77A),
  boardHole: Color(0xFFFFF0CC),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFFFFC857),
  pieceDark: Color(0xFFE09F3E),
  pieceHighlight: Color(0xFFFFE0A3),
  pieceSelected: Color(0xFFD97706),
  primaryColor: Color(0xFFFFC857),
  primaryDark: Color(0xFFE09F3E),
  primaryLight: Color(0xFFFFE0A3),
  accentColor: Color(0xFFD97706),
  surfaceColor: Color(0xFFFFF9ED),
  surfaceLight: Color(0xFFFFF2D9),
  borderLight: Color(0xFFE7C77A),
  borderGlow: Color(0x55FFC857),
  validMoveColor: Color(0xFF43A047),
  textPrimary: Color(0xFF6B4F1D),
  textSecondary: Color(0xFF8A6A33),
  glassColor: Color(0x16FFC857),
  glassBorder: Color(0x24FFC857),
);

const batmanTheme = GameThemeData(
  id: 'batman',
  name: 'BATMAN',
  emoji: '🦇',
  description: 'Gece tonları ve Gotham havası',
  pieceAsset: 'assets/images/batman/batman.png',
  pieceEmoji: '🦇',
  particles: ['🦇', '🌙', '✨', '⚫'],
  useAssetPiece: true,
  backgroundColor: Color(0xFF05070B),
  backgroundGlow1: Color(0xFF2F80ED),
  backgroundGlow2: Color(0xFF0F172A),
  boardBackground: Color(0xFF0B0F19),
  boardBorder: Color(0xFF1F2937),
  boardHole: Color(0xFF06080E),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFF2F80ED),
  pieceDark: Color(0xFF1D4ED8),
  pieceHighlight: Color(0xFF60A5FA),
  pieceSelected: Color(0xFFFACC15),
  primaryColor: Color(0xFF2F80ED),
  primaryDark: Color(0xFF1D4ED8),
  primaryLight: Color(0xFF60A5FA),
  accentColor: Color(0xFFFACC15),
  surfaceColor: Color(0xFF0B0F19),
  surfaceLight: Color(0xFF121826),
  borderLight: Color(0xFF1F2937),
  borderGlow: Color(0x552F80ED),
  validMoveColor: Color(0xFF22C55E),
  textPrimary: Color(0xFFF8FAFC),
  textSecondary: Color(0xFFCBD5E1),
  glassColor: Color(0x162F80ED),
  glassBorder: Color(0x242F80ED),
);

const stitchTheme = GameThemeData(
  id: 'stitch',
  name: 'STITCH',
  emoji: '👽',
  description: 'Mavi kaos ve Lilo & Stitch enerjisi',
  pieceAssets: [
    'assets/images/stitch/stitch.png',
    'assets/images/stitch/rosa.png',
  ],
  pieceAsset: null,
  pieceEmoji: '👽',
  particles: ['👽', '🌺', '✨', '💙'],
  useAssetPiece: true,
  backgroundColor: Color(0xFFEAF6FF),
  backgroundGlow1: Color(0xFF66CCFF),
  backgroundGlow2: Color(0xFF7C4DFF),
  boardBackground: Color(0xFFF3FBFF),
  boardBorder: Color(0xFF9ED8F4),
  boardHole: Color(0xFFDFF4FF),
  boardEmpty: Color(0x00000000),
  piecePrimary: Color(0xFF66CCFF),
  pieceDark: Color(0xFF1D4ED8),
  pieceHighlight: Color(0xFFA6E3FF),
  pieceSelected: Color(0xFFFFB6C1),
  primaryColor: Color(0xFF66CCFF),
  primaryDark: Color(0xFF1D4ED8),
  primaryLight: Color(0xFFA6E3FF),
  accentColor: Color(0xFFFFB6C1),
  surfaceColor: Color(0xFFF3FBFF),
  surfaceLight: Color(0xFFE8F7FF),
  borderLight: Color(0xFF9ED8F4),
  borderGlow: Color(0x5566CCFF),
  validMoveColor: Color(0xFF22C55E),
  textPrimary: Color(0xFF1F4E79),
  textSecondary: Color(0xFF4B7A9E),
  glassColor: Color(0x1666CCFF),
  glassBorder: Color(0x2466CCFF),
);

// All themes map in the desired display order
const Map<GameTheme, GameThemeData> allThemes = {
  GameTheme.classic: classicTheme,
  GameTheme.cat: catTheme,
  GameTheme.hellokitty: hellokittyTheme,
  GameTheme.cars: carsTheme,
  GameTheme.fruits: fruitsTheme,
  GameTheme.powerpuffGirls: powerpuffGirlsTheme,
  GameTheme.spiderman: spidermanTheme,
  GameTheme.sungerbob: sungerbobTheme,
  GameTheme.winniePooh: winniePoohTheme,
  GameTheme.batman: batmanTheme,
  GameTheme.stitch: stitchTheme,
};
